import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {drivers,defaultGrid,type Driver} from './data/drivers';
import {scorePlayer,SCORING_RULES} from './utils/scoring';
import './styles.css';

type HistoryItem={round:string;date:string;vova:number;tshy:number;totalVova:number;totalTshy:number};
const store=(key:string,fallback:string)=>{try{return localStorage.getItem(key)||fallback}catch{return fallback}};
const parse=(key:string,fallback:any)=>{try{return JSON.parse(store(key,JSON.stringify(fallback)))}catch{return fallback}};
const avatarFallback=(name:string,color:string)=>`data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="96" height="96"><rect width="96" height="96" fill="${color}"/><text x="50%" y="58%" text-anchor="middle" font-family="Arial" font-size="42" font-weight="700" fill="#fff">${name[0]}</text></svg>`)}`;

function App(){
 const [tab,setTab]=useState<'dashboard'|'history'>('dashboard'); const [round,setRound]=useState('01'); const [toast,setToast]=useState('');
 const [vova,setVova]=useState<Driver[]>(()=>parse('gridline-vova',defaultGrid())); const [tshy,setTshy]=useState<Driver[]>(()=>parse('gridline-tshy',defaultGrid().slice().reverse())); const [result,setResult]=useState<Driver[]>(()=>parse('gridline-result',defaultGrid().slice().reverse()));
 const [vovaFL,setVovaFL]=useState<Driver>(()=>parse('gridline-vova-fl',drivers[7])); const [tshyFL,setTshyFL]=useState<Driver>(()=>parse('gridline-tshy-fl',drivers[7])); const [resultFL,setResultFL]=useState<Driver>(()=>parse('gridline-result-fl',drivers[7]));
 const [history,setHistory]=useState<HistoryItem[]>(()=>parse('gridline-history',[])); const [avatars,setAvatars]=useState(()=>parse('gridline-avatars',{vova:avatarFallback('V','#e84b5a'),tshy:avatarFallback('T','#24cbd0')}));
 const [winner,setWinner]=useState(()=>store('gridline-winner','https://images.unsplash.com/photo-1617654112368-307921291f42?auto=format&fit=crop&w=900&q=80')); const [tweet,setTweet]=useState(()=>store('gridline-tweet','GEORGE RUSSELL WINS #F1SPRINT AT ZANDVOORT!!!'));
 const total=useMemo(()=>history.reduce((a:{vova:number;tshy:number},h:HistoryItem)=>({vova:a.vova+h.vova,tshy:a.tshy+h.tshy}),{vova:0,tshy:0}),[history]);
 useEffect(()=>{localStorage.setItem('gridline-vova',JSON.stringify(vova));localStorage.setItem('gridline-tshy',JSON.stringify(tshy));localStorage.setItem('gridline-result',JSON.stringify(result));localStorage.setItem('gridline-history',JSON.stringify(history));},[vova,tshy,result,history]);
 const updateAvatar=(who:'vova'|'tshy',file?:File)=>{if(!file)return; const fr=new FileReader(); fr.onload=()=>{const next={...avatars,[who]:fr.result};setAvatars(next);localStorage.setItem('gridline-avatars',JSON.stringify(next))};fr.readAsDataURL(file)};
 const apply=()=>{const vp=scorePlayer(vova,result,vovaFL,resultFL),tp=scorePlayer(tshy,result,tshyFL,resultFL); const item={round,date:new Date().toLocaleDateString('en-GB'),vova:vp,tshy:tp,totalVova:total.vova+vp,totalTshy:total.tshy+tp};setHistory([item,...history]);setToast('Result applied');setTimeout(()=>setToast(''),2200)};
 return <div className="app"><header><div className="logo">GRIDLINE</div><nav><button className={tab==='dashboard'?'active':''} onClick={()=>setTab('dashboard')}>DASHBOARD</button><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}>HISTORY</button></nav></header>
 {tab==='history'?<History history={history}/>:<><section className="hero"><div><h1>RACE DAY, <em>PREDICTED.</em></h1><p>SUBMIT YOUR PICKS, SCORE POINTS, AND DECIDE WHO TAKES THE CHAMPIONSHIP.</p></div><label className="round">ROUND <input value={round} maxLength={2} onChange={e=>setRound(e.target.value.replace(/\D/g,''))}/></label></section>
 <ScoreCard avatars={avatars} setTab={setTab} updateAvatar={updateAvatar} vova={total.vova} tshy={total.tshy}/><Scoring/>
 <div className="section-head"><div><span>RACE PREDICTIONS</span><h2>Predictions &amp; result</h2></div><button className="apply" onClick={apply}>APPLY RESULT</button></div>
 <section className="prediction-layout"><PredictionGrid title="VOVA" accent="#ff4d5e" grid={vova} setGrid={setVova} fl={vovaFL} setFL={setVovaFL}/><WinnerCard image={winner} setImage={x=>{setWinner(x);localStorage.setItem('gridline-winner',x)}} tweet={tweet} setTweet={x=>{setTweet(x);localStorage.setItem('gridline-tweet',x)}} round={round}/><PredictionGrid title="T-SHY" accent="#2bd6d8" grid={tshy} setGrid={setTshy} fl={tshyFL} setFL={setTshyFL}/></section>
 <div className="section-head result-head"><div><span>RACE PREDICTIONS</span><h2>Race result</h2></div></div><ResultGrid grid={result} setGrid={setResult} fl={resultFL} setFL={setResultFL}/></>}
 {toast&&<div className="toast">✓ {toast}</div>}</div>
}
function ScoreCard({avatars,updateAvatar,vova,tshy}:{avatars:any;updateAvatar:(w:'vova'|'tshy',f?:File)=>void;setTab:any;vova:number;tshy:number}){const Upload=({who}:{who:'vova'|'tshy'})=><label className="avatar"><img src={avatars[who]}/><span>✎</span><input type="file" accept="image/*" onChange={e=>updateAvatar(who,e.target.files?.[0])}/></label>;return <section className="score-card"><div className="player p1"><Upload who="vova"/><div><small>PLAYER 01</small><strong>VOVA</strong></div></div><div className="score"><span>Point</span><b>{String(vova).padStart(3,'0')}</b><i>VS</i><b className="cyan">{String(tshy).padStart(3,'0')}</b><span>Point</span></div><div className="player p2"><div><small>PLAYER 02</small><strong>T-SHY</strong></div><Upload who="tshy"/></div></section>}
function Scoring(){return <section className="scoring"><span className="eyebrow">SCORING SYSTEM</span><h2>Scoring rules</h2><div className="rules">{[['exact','Exact position','Prediction matches the result','#ff4d5e'],['range','Range','Driver within top-5 of predicted position','#d4a63e'],['fastestLap','Fastest lap','Separate bonus for fastest lap','#26d9dc'],['miss','Miss','Driver was not predicted','#59606d']].map(([key,title,sub,color])=><div className="rule" key={key}><i style={{background:color}}/><div><b>{title}</b><small>{sub}</small></div><strong style={{color}}>+{SCORING_RULES[key as keyof typeof SCORING_RULES]}</strong><small>pts</small></div>)}</div></section>}
function DriverSelect({value,onChange}:{value:Driver;onChange:(d:Driver)=>void}){return <select value={value.id} onChange={e=>onChange(drivers.find(d=>d.id===e.target.value)!)}>{drivers.map(d=><option value={d.id} key={d.id}>{d.first} {d.last} · {d.team}</option>)}</select>}
function Fastest({value,onChange}:{value:Driver;onChange:(d:Driver)=>void}){return <div className="fastest"><span>ϟ FASTEST LAP</span><DriverSelect value={value} onChange={onChange}/></div>}
function PredictionGrid({title,accent,grid,setGrid,fl,setFL}:{title:string;accent:string;grid:Driver[];setGrid:(x:Driver[])=>void;fl:Driver;setFL:(x:Driver)=>void}){const [drag,setDrag]=useState<number|null>(null); const dup=grid.map(d=>d.id).filter((d,i,a)=>a.indexOf(d)!==i);return <div className="grid-column"><h3 style={{'--accent':accent} as React.CSSProperties}>{title}</h3><Fastest value={fl} onChange={setFL}/><div className="cards">{grid.map((d,i)=><div className={`driver-card ${dup.includes(d.id)?'duplicate':''}`} draggable onDragStart={()=>setDrag(i)} onDragOver={e=>e.preventDefault()} onDrop={()=>{if(drag===null)return;const next=grid.slice();const [m]=next.splice(drag,1);next.splice(i,0,m);setGrid(next);setDrag(null)}} key={i} style={{'--team':d.color} as React.CSSProperties}><span className="position">{String(i+1).padStart(2,'0')}</span><span className="driver-name"><em>{d.first.toUpperCase()}</em><b>{d.last.toUpperCase()}</b><small>{d.team} · ⓘ</small></span><DriverSelect value={d} onChange={x=>{const n=grid.slice();n[i]=x;setGrid(n)}}/><strong className="points">{i===0?12: i<3?10:8}</strong><span className="chevron">⌄</span></div>)}</div></div>}
function ResultGrid({grid,setGrid,fl,setFL}:{grid:Driver[];setGrid:(x:Driver[])=>void;fl:Driver;setFL:(x:Driver)=>void}){return <div className="result-grid"><Fastest value={fl} onChange={setFL}/><div className="result-cards">{grid.map((d,i)=><div className="driver-card" key={i} style={{'--team':d.color} as React.CSSProperties}><span className="position">{String(i+1).padStart(2,'0')}</span><span className="driver-name"><em>{d.first.toUpperCase()}</em><b>{d.last.toUpperCase()}</b><small>{d.team} · ⓘ</small></span><DriverSelect value={d} onChange={x=>{const n=grid.slice();n[i]=x;setGrid(n)}}/><strong className="points">{i===0?12:i<3?10:8}</strong><span className="chevron">⌄</span></div>)}</div></div>}
function WinnerCard({image,setImage,tweet,setTweet,round}:{image:string;setImage:(x:string)=>void;tweet:string;setTweet:(x:string)=>void;round:string}){return <div className="winner-card"><h3>LAST RACE WINNER</h3><div className="tweet-head"><b>▰ Formula 1</b><small>@F1</small></div><input className="tweet-input" value={tweet} onChange={e=>setTweet(e.target.value)}/><label className="winner-image"><img src={image}/><span>↗ Replace image</span><input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>setImage(String(r.result));r.readAsDataURL(f)}}/></label><div className="winner-label"><b>WINNER</b><span>SPRINT // ROUND {round} // NETHERLANDS</span><small>GATORADE</small></div></div>}
function History({history}:{history:HistoryItem[]}){return <main className="history-page"><div className="history-title"><span>ROUND ARCHIVE</span><h1>History</h1><p>Applied results and running championship scores.</p></div>{history.length===0?<div className="empty">No applied rounds yet. Your race history will appear here.</div>:history.map((h,i)=><article className="history-card" key={i}><div><span>ROUND {h.round} · {h.date}</span><h2>VOVA <b>{h.vova}</b> <i>VS</i> <b className="cyan">{h.tshy}</b> T-SHY</h2></div><div className="running">RUNNING SCORE<strong>{h.totalVova} — {h.totalTshy}</strong></div></article>)}</main>}
createRoot(document.getElementById('root')!).render(<App/>);
