import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {DndContext,PointerSensor,useSensor,useSensors,type DragEndEvent} from '@dnd-kit/core';
import {SortableContext,verticalListSortingStrategy,useSortable} from '@dnd-kit/sortable';
import {CSS} from '@dnd-kit/utilities';
import {drivers,type Driver} from './data/drivers';
import {type AppState,type HistoryItem} from './data/appState';
import {loadSharedState,saveSharedState} from './data/storage';
import {scorePlayer,SCORING_RULES} from './utils/scoring';
import './styles.css';
import './picker.css';
import './picker-layout.css';
import './layout-fixes.css';
import './auth.css';

type PickerControl={openPickerId:string|null;setOpenPickerId:(id:string|null)=>void};

function App(){
 const [tab,setTab]=useState<'dashboard'|'history'>('dashboard'); const [state,setState]=useState<AppState|null>(null); const [loadError,setLoadError]=useState<string|null>(null); const [toast,setToast]=useState(''); const [saving,setSaving]=useState(false); const [isAdmin,setIsAdmin]=useState(()=>localStorage.getItem('gridline-admin-session')==='1'); const [loginOpen,setLoginOpen]=useState(false); const [password,setPassword]=useState(''); const [loginError,setLoginError]=useState(''); const [openPickerId,setOpenPickerId]=useState<string|null>(null);
 const configuredPassword=import.meta.env.VITE_ADMIN_PASSWORD as string|undefined;
 const login=()=>{if(password&&configuredPassword&&password===configuredPassword){localStorage.setItem('gridline-admin-session','1');setIsAdmin(true);setLoginOpen(false);setPassword('');setLoginError('')}else setLoginError(configuredPassword?'Incorrect password':'Admin login is not configured')};
 const logout=()=>{localStorage.removeItem('gridline-admin-session');setIsAdmin(false)};
 const saveQueue=useRef(Promise.resolve());
 const load=()=>{setLoadError(null);setState(null);loadSharedState().then(result=>{console.log(`[GRIDLINE] State loaded from ${result.source}.`);if(result.error){setLoadError(result.error);return}setState(result.state);if(result.source==='supabase')saveSharedState(result.state).then(()=>console.log('[GRIDLINE] Normalized shared state saved.')).catch(error=>console.warn('[GRIDLINE] Could not save normalized shared state.',error))})};
 useEffect(load,[]);
 if(!state) return <div className="app loading" style={{minHeight:'100vh',display:'grid',placeItems:'center',color:'#777',textAlign:'center'}}>{loadError?<div><p>Unable to load shared GRIDLINE state.</p><button onClick={load}>RETRY</button></div>:'LOADING SHARED GRIDLINE STATE…'}</div>;
 const commit=(next:AppState,message?:string)=>{setState(next);setSaving(true);saveQueue.current=saveQueue.current.catch(()=>undefined).then(()=>saveSharedState(next)).then(()=>console.log('[GRIDLINE] State saved.')).catch(error=>{console.error('[GRIDLINE] State save failed.',error);setToast('Shared save failed');setTimeout(()=>setToast(''),2800)}).finally(()=>setSaving(false));if(message){setToast(message);setTimeout(()=>setToast(''),2200)}};
 const set=(patch:Partial<AppState>)=>commit({...state,...patch});
 const apply=()=>{const vp=scorePlayer(state.vova,state.result,state.vovaFL,state.resultFL),tp=scorePlayer(state.tshy,state.result,state.tshyFL,state.resultFL);const item={round:state.round,date:new Date().toLocaleDateString('en-GB'),vova:vp,tshy:tp,totalVova:state.scores.vova+vp,totalTshy:state.scores.tshy+tp};commit({...state,history:[item,...state.history],scores:{vova:item.totalVova,tshy:item.totalTshy}},'Result applied')};
 const reset=()=>{if(!window.confirm("Are you sure you want to reset both players' scores to 0 and clear all round history? This cannot be undone."))return;commit({...state,history:[],scores:{vova:0,tshy:0}},'Scores and history reset')};
 const updateAvatar=(who:'vova'|'tshy',file?:File)=>{if(!file)return;const fr=new FileReader();fr.onload=()=>set({avatars:{...state.avatars,[who]:String(fr.result)}});fr.readAsDataURL(file)};
 return <div className="app"><header><div className="logo">GRIDLINE</div><div className="header-actions"><nav><button className={tab==='dashboard'?'active':''} onClick={()=>setTab('dashboard')}>DASHBOARD</button><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}>HISTORY</button></nav><button className={`login-button ${isAdmin?'logged-in':''}`} onClick={()=>isAdmin?logout():setLoginOpen(true)}>{isAdmin?'◉ LOGGED IN':'LOG IN'}</button></div></header>{loginOpen&&<div className="login-modal"><form onSubmit={e=>{e.preventDefault();login()}}><div className="login-modal-title">ADMIN ACCESS</div><input autoFocus type="password" placeholder="Shared password" value={password} onChange={e=>{setPassword(e.target.value);setLoginError('')}}/><button type="submit">UNLOCK EDITING</button>{loginError&&<p>{loginError}</p>}</form></div>}
 {tab==='history'?<History history={state.history}/>:<><section className="hero"><div><h1>RACE DAY, <em>PREDICTED.</em></h1><p>SUBMIT YOUR PICKS, SCORE POINTS, AND DECIDE WHO TAKES THE CHAMPIONSHIP.</p></div><label className="round">ROUND <input disabled={!isAdmin} value={state.round} maxLength={2} onChange={e=>set({round:e.target.value.replace(/\D/g,'')})}/></label></section>
 <ScoreCard editable={isAdmin} avatars={state.avatars} updateAvatar={updateAvatar} vova={state.scores.vova} tshy={state.scores.tshy}/><Scoring/>
 <div className="section-head"><div><span>RACE PREDICTIONS</span><h2>Predictions &amp; result</h2></div><div className="action-buttons" style={{display:'flex',gap:9,alignItems:'flex-start',marginBottom:31}}><button disabled={!isAdmin} className="reset" onClick={reset} style={{background:'#191b1f',border:'1px solid #3c424a',color:'#c6cbd1',borderRadius:9,padding:'13px 29px',fontSize:10,fontWeight:700,height:42,opacity:isAdmin?1:.45}}>RESET</button><button disabled={!isAdmin} className="apply" onClick={apply} style={{height:42,opacity:isAdmin?1:.45}}>APPLY RESULT</button></div></div>
 <section className="prediction-layout"><PredictionGrid picker={{openPickerId,setOpenPickerId}} editable={isAdmin} title="VOVA" accent="#ff4d5e" grid={state.vova} setGrid={grid=>set({vova:grid})} fl={state.vovaFL} setFL={vovaFL=>set({vovaFL})}/><WinnerCard editable={isAdmin} image={state.winner} setImage={winner=>set({winner})} tweet={state.tweet} setTweet={tweet=>set({tweet})}/><PredictionGrid picker={{openPickerId,setOpenPickerId}} editable={isAdmin} title="T-SHY" accent="#2bd6d8" grid={state.tshy} setGrid={grid=>set({tshy:grid})} fl={state.tshyFL} setFL={tshyFL=>set({tshyFL})}/></section>
 <div className="section-head result-head"><div><span>RACE PREDICTIONS</span><h2>Race result</h2></div></div><ResultGrid picker={{openPickerId,setOpenPickerId}} editable={isAdmin} grid={state.result} setGrid={result=>set({result})} fl={state.resultFL} setFL={resultFL=>set({resultFL})}/></>}
 {saving&&<div className="save-status" style={{position:'fixed',left:28,bottom:28,color:'#777',fontSize:9,letterSpacing:1}}>SAVING SHARED STATE…</div>}{toast&&<div className="toast">✓ {toast}</div>}</div>
}
function ScoreCard({editable,avatars,updateAvatar,vova,tshy}:{editable:boolean;avatars:AppState['avatars'];updateAvatar:(w:'vova'|'tshy',f?:File)=>void;vova:number;tshy:number}){const Upload=({who}:{who:'vova'|'tshy'})=><label className={`avatar ${editable?'':'readonly-control'}`}><img src={avatars[who]}/><span>✎</span><input disabled={!editable} type="file" accept="image/*" onChange={e=>updateAvatar(who,e.target.files?.[0])}/></label>;return <section className="score-card"><div className="player p1"><Upload who="vova"/><div><small>PLAYER 01</small><strong>VOVA</strong></div></div><div className="score"><span>Point</span><b>{String(vova).padStart(3,'0')}</b><i>VS</i><b className="cyan">{String(tshy).padStart(3,'0')}</b><span>Point</span></div><div className="player p2"><div><small>PLAYER 02</small><strong>T-SHY</strong></div><Upload who="tshy"/></div></section>}
function Scoring(){return <section className="scoring"><span className="eyebrow">SCORING SYSTEM</span><h2>Scoring rules</h2><div className="rules">{[['exact','Exact position','Prediction matches the result','#ff4d5e'],['range','Range','Driver within top-5 of predicted position','#d4a63e'],['fastestLap','Fastest lap','Separate bonus for fastest lap','#26d9dc'],['miss','Miss','Driver was not predicted','#59606d']].map(([key,title,sub,color])=><div className="rule" key={key}><i style={{background:color}}/><div><b>{title}</b><small>{sub}</small></div><strong style={{color}}>+{SCORING_RULES[key as keyof typeof SCORING_RULES]}</strong><small>pts</small></div>)}</div></section>}
function DriverPicker({value,onChange,blockedIds=[],disabled=false,compact=false,pickerId,picker}:{value:Driver;onChange:(d:Driver)=>void;blockedIds?:string[];disabled?:boolean;compact?:boolean;pickerId:string;picker:PickerControl}){const open=picker.openPickerId===pickerId;return <div className={`driver-picker ${disabled?'readonly-control':''}`}><button disabled={disabled} className={`picker-trigger ${compact?'compact':''}`} type="button" onClick={e=>{e.stopPropagation();picker.setOpenPickerId(open?null:pickerId)}}>{!compact&&<span className="picker-label">{value.first.toUpperCase()} <b>{value.last.toUpperCase()}</b> <i>#{value.number}</i></span>}<span className="picker-arrow">⌄</span></button>{open&&<div className="picker-menu" onClick={e=>e.stopPropagation()}>{drivers.map(d=>{const blocked=blockedIds.includes(d.id)&&d.id!==value.id;return <button type="button" className={blocked?'blocked':''} disabled={blocked} key={d.id} onClick={()=>{onChange(d);picker.setOpenPickerId(null)}}><span>{d.first} {d.last} <b>#{d.number}</b></span><small>{d.team}</small><strong>{d.id===value.id?'✓':''}</strong></button>})}</div>}</div>}
function Fastest({value,onChange,blockedIds=[],editable=true,picker,pickerId}:{value:Driver;onChange:(d:Driver)=>void;blockedIds?:string[];editable?:boolean;picker:PickerControl;pickerId:string}){return <div className={`fastest ${editable?'':'readonly-control'}`}><span>ϟ FASTEST LAP</span><DriverPicker picker={picker} pickerId={pickerId} disabled={!editable} value={value} onChange={onChange} blockedIds={blockedIds}/></div>}
function SortableDriverCard({editable,driver,index,grid,setGrid,blockedIds,picker,pickerId}:{editable:boolean;driver:Driver;index:number;grid:Driver[];setGrid:(x:Driver[])=>void;blockedIds:string[];picker:PickerControl;pickerId:string}){const {attributes,listeners,setNodeRef,transform,transition,isDragging}=useSortable({id:driver.id});const next=(driver:Driver)=>{const n=grid.slice();n[index]=driver;setGrid(n)};const openPicker=(e:React.MouseEvent<HTMLDivElement>)=>{if(!editable||(e.target as HTMLElement).closest('.driver-picker'))return;(e.currentTarget.querySelector('.picker-trigger') as HTMLButtonElement|null)?.click()};return <div ref={setNodeRef} className="driver-card" onClick={editable?openPicker:undefined} style={{'--team':driver.color,transform:CSS.Transform.toString(transform),transition,opacity:isDragging?.55:1} as React.CSSProperties} {...(editable?attributes:{})} {...(editable?listeners:{})}><span className="position">{String(index+1).padStart(2,'0')}</span><span className="driver-name"><em>{driver.first.toUpperCase()}</em><b>{driver.last.toUpperCase()}</b><i className="driver-number">#{driver.number}</i><small>{driver.team} · ⓘ</small></span><DriverPicker compact picker={picker} pickerId={pickerId} disabled={!editable} value={driver} onChange={next} blockedIds={blockedIds}/><strong className="points driver-number-badge">#{driver.number}</strong></div>}
function PredictionGrid({editable,title,accent,grid,setGrid,fl,setFL,picker}:{editable:boolean;title:string;accent:string;grid:Driver[];setGrid:(x:Driver[])=>void;fl:Driver;setFL:(x:Driver)=>void;picker:PickerControl}){const sensors=useSensors(useSensor(PointerSensor,{activationConstraint:{distance:8}}));const blocked=grid.map(d=>d.id);const onDragEnd=({active,over}:DragEndEvent)=>{if(!editable||!over||active.id===over.id)return;const from=grid.findIndex(d=>d.id===active.id);const to=grid.findIndex(d=>d.id===over.id);if(from<0||to<0)return;const next=grid.slice();const [moved]=next.splice(from,1);next.splice(to,0,moved);setGrid(next)};return <div className="grid-column"><h3 style={{'--accent':accent} as React.CSSProperties}>{title}</h3><DndContext sensors={editable?sensors:[]} onDragEnd={onDragEnd}><Fastest picker={picker} pickerId={`${title}-fastest`} editable={editable} value={fl} onChange={setFL} blockedIds={blocked}/><SortableContext items={grid.map(d=>d.id)} strategy={verticalListSortingStrategy}><div className="cards">{grid.map((driver,index)=><SortableDriverCard key={driver.id} picker={picker} pickerId={`${title}-position-${index}`} editable={editable} driver={driver} index={index} grid={grid} setGrid={setGrid} blockedIds={blocked.filter(id=>id!==driver.id)}/>)}</div></SortableContext></DndContext></div>}
function SortableResultCard({editable,driver,index,grid,setGrid,blockedIds,picker}:{editable:boolean;driver:Driver;index:number;grid:Driver[];setGrid:(x:Driver[])=>void;blockedIds:string[];picker:PickerControl}){const {attributes,listeners,setNodeRef,transform,transition,isDragging}=useSortable({id:`result-${driver.id}`});const next=(selected:Driver)=>{const n=grid.slice();n[index]=selected;setGrid(n)};const openPicker=(e:React.MouseEvent<HTMLDivElement>)=>{if(!editable||(e.target as HTMLElement).closest('.driver-picker'))return;(e.currentTarget.querySelector('.picker-trigger') as HTMLButtonElement|null)?.click()};return <div ref={setNodeRef} className="driver-card" onClick={editable?openPicker:undefined} style={{'--team':driver.color,transform:CSS.Transform.toString(transform),transition,opacity:isDragging?.55:1} as React.CSSProperties} {...(editable?attributes:{})} {...(editable?listeners:{})}><span className="position">{String(index+1).padStart(2,'0')}</span><span className="driver-name"><em>{driver.first.toUpperCase()}</em><b>{driver.last.toUpperCase()}</b><i className="driver-number">#{driver.number}</i><small>{driver.team} · ⓘ</small></span><DriverPicker compact picker={picker} pickerId={`result-position-${index}`} disabled={!editable} value={driver} onChange={next} blockedIds={blockedIds}/><strong className="points driver-number-badge">#{driver.number}</strong></div>}
function ResultGrid({editable,grid,setGrid,fl,setFL,picker}:{editable:boolean;grid:Driver[];setGrid:(x:Driver[])=>void;fl:Driver;setFL:(x:Driver)=>void;picker:PickerControl}){const sensors=useSensors(useSensor(PointerSensor,{activationConstraint:{distance:8}}));const blocked=grid.map(d=>d.id);const onDragEnd=({active,over}:DragEndEvent)=>{if(!editable||!over||active.id===over.id)return;const from=grid.findIndex(d=>`result-${d.id}`===active.id);const to=grid.findIndex(d=>`result-${d.id}`===over.id);if(from<0||to<0)return;const next=grid.slice();const [moved]=next.splice(from,1);next.splice(to,0,moved);setGrid(next)};return <div className="result-grid"><DndContext sensors={editable?sensors:[]} onDragEnd={onDragEnd}><Fastest picker={picker} pickerId="result-fastest" editable={editable} value={fl} onChange={setFL} blockedIds={blocked}/><SortableContext items={grid.map(d=>`result-${d.id}`)} strategy={verticalListSortingStrategy}><div className="result-cards">{grid.map((d,i)=><SortableResultCard key={d.id} picker={picker} editable={editable} driver={d} index={i} grid={grid} setGrid={setGrid} blockedIds={blocked.filter(id=>id!==d.id)}/>)}</div></SortableContext></DndContext></div>}
function WinnerCard({editable,image,setImage,tweet,setTweet}:{editable:boolean;image:string;setImage:(x:string)=>void;tweet:string;setTweet:(x:string)=>void}){return <div className={`winner-card ${editable?'':'readonly-control'}`}><h3>LAST RACE WINNER</h3><div className="tweet-head"><b>▰ Formula 1</b><small>@F1</small></div><input disabled={!editable} readOnly={!editable} className="tweet-input" value={tweet} onChange={e=>setTweet(e.target.value)}/><label className="winner-image"><img src={image}/><input disabled={!editable} type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>setImage(String(r.result));r.readAsDataURL(f)}}/></label></div>}
function History({history}:{history:HistoryItem[]}){return <main className="history-page"><div className="history-title"><span>ROUND ARCHIVE</span><h1>History</h1><p>Applied results and running championship scores.</p></div>{history.length===0?<div className="empty">No applied rounds yet. Your race history will appear here.</div>:history.map((h,i)=><article className="history-card" key={i}><div><span>ROUND {h.round} · {h.date}</span><h2>VOVA <b>{h.vova}</b> <i>VS</i> <b className="cyan">{h.tshy}</b> T-SHY</h2></div><div className="running">RUNNING SCORE<strong>{h.totalVova} — {h.totalTshy}</strong></div></article>)}</main>}
createRoot(document.getElementById('root')!).render(<App/>);
